[package]
name = "polyzdb"
version = "0.1.0"
authors = ["clickingbuttons"]
edition = "2018"

[dependencies]
chrono = "0.4"
threadpool = "1.8.1"
polygon_io = { path = "../polygon_io" }
zdb = { path = "../zdb" }

[profile.release]
debug = true

